### ISSUE TITLE
Illegal file name...

### ISSUE THREAD

**Issue by Ranx0r0x** [Vantiv/litle-sdk-for-java#40]
The following file name created by the batch process is illegal in Windows environments.

batchFolder/tmp/Transactions01802015-07-02 22:36:30.918

**Comment by Ranx0r0x** [comment]
OSGi bundle.

For use in ESBs such as Fuse and ServiceMix, Felix, Equinox, Karaf, ServiceMix, Glassfish, etc. it would be good if the library were packaged as an OSGi bundle.  It isn't difficult and wouldn't require a lot of extra work.  Mostly some Maven configurations.

**Comment by Ranx0r0x** [comment]
For use in ESBs such as Fuse and ServiceMix, Felix, Equinox, Karaf, ServiceMix, Glassfish, etc. it would be good if the library were packaged as an OSGi bundle. It isn't difficult and wouldn't require a lot of extra work. Mostly some Maven configurations.

**Comment by brianarnold789** [comment]
closing old issues, please reopen if still needed
