### ISSUE TITLE
SSLHandshakeException on Sandbox

### ISSUE THREAD

**Issue by thallium205** [Vantiv/litle-sdk-for-java#43]
My unit tests are failing for Litle these days where they used to work.  Below is the exception I am receiving. I am using the latest SDK as of today (8.29.3) and am using the following sandbox URL:
url=https://www.testlitle.com/sandbox/communicator/online

``` java
com.litle.sdk.LitleOnlineException: Exception connection to Litle
    at com.litle.sdk.Communication.requestToServer(Communication.java:81)
    at com.litle.sdk.LitleOnline.sendToLitle(LitleOnline.java:679)
    at com.litle.sdk.LitleOnline.sale(LitleOnline.java:332)
    at com.litle.sdk.LitleOnline.sale(LitleOnline.java:324)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:533)
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:401)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    at com.litle.sdk.Communication.requestToServer(Communication.java:70)
    ... 33 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
    at sun.security.ssl.InputRecord.read(InputRecord.java:482)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
```

Did the testing endpoint change?

**Comment by thallium205** [comment]
This is how I am instantiating the LitleOnline object:

```java
Properties properties = new Properties();
properties.setProperty("merchantId", "ididid");
properties.setProperty("username", "JoesStore");
properties.setProperty("password", "JoeyIsTheBe$t");
properties.setProperty("url", "https://www.testlitle.com/sandbox/communicator/online");
LitleOnline litleOnline = new LitleOnline(properties);
```

Any sort of call using litleOnline results in the SSLHandshakeException

**Comment by litleSDK** [comment]
We recently chamged our TLS to be V1.2 on our sandbox.

I apologize for the inconvenience in your testing, can you run tests using TLS 1.2.

**Comment by thallium205** [comment]
I am able to communicate with the test server at 96.126.97.71 by manually adding TLSv1.2 as an enabled protocol when doing a GET.  However, the library is not doing this explicit add of this TLS version.  Is there some kind of explicit way of setting TLSv1.2 in the library?  Or is there some sort of way of setting it in the environment?

Executing this:
```java
        try {
            String host = "96.126.97.71";
            SSLSocketFactory factory =
                    (SSLSocketFactory) SSLSocketFactory.getDefault();
            SSLSocket socket = (SSLSocket) factory.createSocket(host, 443);
            String[] protocols = socket.getEnabledProtocols();
            System.out.println("Enabled Protocols: ");
            for (int i = 0; i < protocols.length; i++) {
                System.out.println(protocols[i] + ", ");
            }
            String[] supportedProtocols = socket.getSupportedProtocols();
            System.out.println("Supported Protocols: ");
            for (int i = 0; i < protocols.length; i++) {
                System.out.println(supportedProtocols[i] + ", ");
            }
            String[] goodProtocols = new String[1];
            goodProtocols[0] = "TLSv1.2";
            socket.setEnabledProtocols(goodProtocols);
            protocols = socket.getEnabledProtocols();
            System.out.println("Set Protocols: ");
            for (int i = 0; i < protocols.length; i++) {
                System.out.println(protocols[i] + ", ");
            }

            socket.startHandshake();

            PrintWriter out = new PrintWriter(
                    new BufferedWriter(
                            new OutputStreamWriter(
                                    socket.getOutputStream())));

            out.println("GET / HTTP/1.0");
            out.println();
            out.flush();

            if (out.checkError())
                System.out.println(
                        "SSLSocketClient:  java.io.PrintWriter error");

            BufferedReader in = new BufferedReader(
                    new InputStreamReader(
                            socket.getInputStream()));

            String inputLine;
            while ((inputLine = in.readLine()) != null)
                System.out.println(inputLine);

            in.close();
            out.close();
            socket.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
```

Results in this:
```java
TLSv1,TLSv1.1,TLSv1.2
Enabled Protocols: 
SSLv3, 
TLSv1, 
Supported Protocols: 
SSLv2Hello, 
SSLv3, 
Set Protocols: 
TLSv1.2, 
Added Enabled Protocols: 
TLSv1.2, 
HTTP/1.1 200 OK
Date: Wed, 30 Sep 2015 00:52:10 GMT
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 363
Set-Cookie: JSESSIONID=B1360CD88C2AE1967D16C1729E658121; Path=/; HttpOnly
Connection: close

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title>Developers</title>
<meta http-equiv="REFRESH" content="3;url=http://www.litle.com/developers"></HEAD>
<BODY>
You are being redirected to http://www.litle.com/developers.  If you are not redirected, please click <a href="http://www.litle.com/developers">Here</a>.
</BODY>
</HTML>
```

As you can see, I am only able to contact the TLSv1.2 test server when I add it to the socket under setEnabledProtocols.

**Comment by thallium205** [comment]
I noticed this pull request -> https://github.com/LitleCo/litle-sdk-for-java/pull/42

I built from source and it is now working.  Perhaps another release build is in order?  Thanks for the help!

**Comment by mdaijazyousuf** [comment]
Hi How do we build the Litle jar?  I have made the above changes for TLS1.2 and now i am trying to build the jar using the build.gradle but i am getting exceptions with Annotations :

symbol  : method required()
location: @interface javax.xml.bind.annotation.XmlElementRef
    @XmlElementRef(name = "recurringTransaction", namespace = "http://www.litle.com/schema", type = JAXBElement.class, required = false)
                                                                                                                       ^
C:\Users\maijaz-yousuf\Downloads\litle-sdk-for-java-9.3.1\litle-sdk-for-java-9.3.1\build\generated\com\litle\sdk\generate\BatchRequest.java:116: cannot find symbol
symbol  : method required()
location: @interface javax.xml.bind.annotation.XmlElementRef
    @XmlElementRef(name = "transaction", namespace = "http://www.litle.com/schema", type = JAXBElement.class, required = false)
                                                                                                              ^
C:\Users\maijaz-yousuf\Downloads\litle-sdk-for-java-9.3.1\litle-sdk-for-java-9.3.1\build\generated\com\litle\sdk\generate\BatchResponse.java:53: cannot find symbol
symbol  : method required()

Can you please let me know what needs to be done to build the project?

**Comment by mdaijazyousuf** [comment]
I was able to make it work by placing the jaxb-api-2.2.jar in endorsed folder in jdk/jre/lib. So please ignore the above error

**Comment by mdaijazyousuf** [comment]
Hi, the code provided for making TLS1,2 protocol works only with HttpCliient 4.2.x versions and higher. We are having some issues with deploying this code in Websphere Server as websphere has inbuilt plugin jar (com.ibm.ws.prereq.jaxrs.jar, which actually refers to httpclient 4.1.x). If we try to add this httpClient 4.2.x to the websphere classpath, we are encountering class conflict issues at the time of Litle invocation. I have also tested by changing the class loaders to read the local classes first and parent last configurations but it doesn't seem to be working. It will be helpful if you can make TLS1.2 related handshake changes backward compatible.

**Comment by brianarnold789** [comment]
closing old issues, please reopen if needed
