### ISSUE TITLE
LitleOnline class has a mistake in the javadoc

### ISSUE THREAD

**Issue by charl8182** [Vantiv/litle-sdk-for-java#46]
In the constructor the reads the following:

"   /**
     \* Construct a LitleOnline specifying the configuration in code.  This should be used by integrations that
     \* have another way to specify their configuration settings (ofbiz, etc)
     *
     \* Properties that _must_ be set are:
     *
     \*  url (eg https://payments.litle.com/vap/communicator/online)
     \*  reportGroup (eg "Default Report Group")
     \*  username
     \*  merchantId
     \*  password
     \*  version (eg 8.10)
     \*  timeout (in seconds)
     \*  Optional properties are:
     \*  proxyHost
     \*  proxyPort
     \*  printxml (possible values "true" and "false" - defaults to false)
     *
     \* @param config
     */"

timeout is in milliseconds, not in seconds as it says

**Comment by brianarnold789** [comment]
closing old issues, please reopen if needed
