### ISSUE TITLE
Publish to jcenter

### ISSUE THREAD

**Issue by mjallday** [Vantiv/litle-sdk-for-java#49]
I cannot find release 9.3.4 on jcenter. https://bintray.com/litlesdk/maven/litle-sdk-for-java shows 9.3.3 as the latest release.

i need to get the fix from https://github.com/LitleCo/litle-sdk-for-java/pull/45 since this client is broken without it.

**Comment by brianarnold789** [comment]
closing old issues, please reopen if needed
